name: StyleCop Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.2' 

    - name: Install StyleCop
      run: dotnet tool install -g StyleCop.Analyzers

    - name: Build and Analyze
      run: dotnet build EatsOnApi.csproj /p:RunAnalyzers=true
